server:
  port: 8080
  readTimeout: 15
  writeTimeout: 15

metrics:
  enabled: true
  port: 9090
  path: "/metrics"

auth:
  enabled: false
  # IMPORTANT: Use a strong, randomly generated secret and manage it securely (e.g., via environment variables or a vault).
  jwtSecret: "AyAPpHYGt5aQ32uB"
  tokenQueryParam: "token"
  revocationListKey: "dev:jwt:revoked"

broker:
  type: "redis"
  redis:
    address: "localhost:6379"
    password: ""
    db: 0
    poolSize: 200
    channels:
      inbound: "dev:ws:inbound"
      outbound: "dev:ws:outbound"
      system: "dev:ws:system"
      connection: "dev:ws:connections"
  kafka:
    brokers: ["localhost:9092"]
    groupID: "websocket-pooler"

websocket:
  maxConnections: 10000
  messageSizeLimit: 4096
  pingInterval: 5
  reconnectBackoff: 500
  maxRetries: 3
  activityTimeout: 10
  keepAlive: true
