apiVersion: apps/v1
kind: Deployment
metadata:
  name: pooler-deployment
  namespace: ws-pooler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pooler
  template:
    metadata:
      labels:
        app: pooler
    spec:
      containers:
      - name: pooler
        image: pooler-app:latest
        imagePullPolicy: Never # Use local image
        ports:
        - containerPort: 8080
        env:
        - name: WSGATEWAY_BROKER_TYPE
          value: "redis"
        - name: WSGATEWAY_REDIS_ADDRESS
          value: "redis:6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pooler-service
  namespace: ws-pooler
spec:
  type: NodePort
  selector:
    app: pooler
  ports:
  - port: 8080
    targetPort: 8080
