apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pooler-hpa
  namespace: ws-pooler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pooler-deployment
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
